apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-dev
  labels:
    app: grafana
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #storageClassName: managed-premium  # can be used in production